import 'package:flutter/material.dart';
import 'package:flutter_app_for_exam2/NewsApp/utils/widgets/articles_widgets/articles_controller.dart';
import 'package:flutter_app_for_exam2/NewsApp/utils/widgets/articles_widgets/bottom_navigation_bar_controller.dart';
import 'package:flutter_app_for_exam2/NewsApp/utils/widgets/bookmark_widgets/bookmark_bottom_navigation_bar.dart';
class Article13Page extends StatelessWidget {
  const Article13Page({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: ArticlesController(image: "assets/images/bookmark_page/image4.png",title: "Travel Destinations That Won't Break the Bank",avatar: "assets/images/explore_page/woman3.png",text1: "Jennie Robertson · May 9, 2023",text2: "Exploring the world on a budget is not only possible but also incredibly rewarding. Here are five travel destinations that offer memorable experiences without breaking the bank:\n1. Vietnam: From the bustling streets of Hanoi to the stunning landscapes of Ha Long Bay and the charming lantern-lit streets of Hoi An, Vietnam offers a wealth of experiences at affordable prices. Enjoy delicious street food for just a few dollars, explore ancient temples and pagodas, and embark on budget-friendly excursions such as trekking in Sapa or cruising on the Mekong Delta.\n2. Portugal: With its rich history, vibrant culture, and stunning coastline, Portugal is a budget traveler's paradise. Explore the colorful streets of Lisbon, indulge in fresh seafood and pastries, and soak up the sun on the beaches of the Algarve. Accommodation, transportation, and dining are all affordable, making Portugal an ideal destination for those seeking an affordable European getaway.\n3. Thailand: Known for its friendly locals, tropical beaches, and vibrant street food scene, Thailand offers incredible value for budget travelers. Explore bustling markets in Bangkok, visit ancient temples in Chiang Mai, and unwind on the picturesque islands of Phuket and Koh Samui. With affordable accommodation options, inexpensive street food, and a range of budget-friendly activities, Thailand is a top choice for travelers on a budget.\n4. Bolivia: Nestled in the heart of South America, Bolivia offers stunning landscapes, rich indigenous culture, and affordable travel options. Explore the otherworldly landscapes of the Salar de Uyuni, visit the historic cities of La Paz and Sucre, and trek in the Andes Mountains. With budget-friendly accommodations, cheap street food, and inexpensive transportation options, Bolivia is a fantastic destination for budget travelers seeking adventure.\n5. Hungary: With its charming capital city of Budapest, historic towns, and scenic countryside, Hungary offers a wealth of experiences at affordable prices. Explore the architectural wonders of Budapest, soak in the thermal baths, and indulge in hearty Hungarian cuisine. Outside the capital, discover charming villages, vineyards, and castles without breaking the bank. Accommodation, dining, and transportation are all budget-friendly, making Hungary an ideal destination for travelers looking to stretch their dollars.These destinations offer incredible experiences, rich culture, and stunning landscapes at prices that won't break the bank. With a bit of planning and savvy budgeting, travelers can enjoy unforgettable adventures without sacrificing quality or comfort.",bottomNavigationBar: const BottomNavigationBarController(),),
        bottomNavigationBar: const BookmarkBottomNavigationBar());
  }
}