import 'package:flutter/material.dart';
import 'package:flutter_app_for_exam2/NewsApp/utils/widgets/articles_widgets/articles_controller.dart';
import 'package:flutter_app_for_exam2/NewsApp/utils/widgets/explore_widgets/explore_bottom_navigation_bar.dart';
class Article9Page extends StatelessWidget {
  const Article9Page({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: ArticlesController(image: "assets/images/bookmark_page/image8.png",title: "A Guide to Seasonal Gardening",avatar: "assets/images/clapped_articles_page/avatar4.png",text1: "Sophie Larkin · May 10, 2023",text2: "Seasonal gardening is a timeless practice deeply rooted in our connection to nature's rhythms. It's an art form, a dance with the earth, where each season offers its own unique set of tasks and rewards.As spring unfolds, the garden awakens from its winter slumber. It's a time of renewal and anticipation, as we prepare the soil, sow seeds, and watch with bated breath as tiny shoots emerge from the ground. The air is filled with the scent of freshly turned earth and the promise of new beginnings.Summer arrives in a blaze of sunshine and warmth, bringing with it a burst of growth and vitality. The garden becomes a riot of color and fragrance, alive with the hum of bees and the flutter of butterflies. We tend to our plants with care, watering, weeding, and harvesting the fruits of our labor. It's a time of abundance, when we can feast on the bounty of our gardens and share the harvest with friends and neighbors.As autumn approaches, the garden begins to wind down, signaling the end of the growing season. We gather the last of the harvest, preserving fruits and vegetables for the months ahead. The air turns crisp, and the leaves take on hues of gold and crimson, painting a picture of beauty and transition. It's a time of reflection, as we look back on the season's successes and failures, and begin to plan for the year ahead.Winter settles in, blanketing the garden in a quiet stillness. The earth rests, dormant beneath a layer of snow and ice. Yet even in the depths of winter, there is life stirring beneath the surface. We turn our attention indoors, nurturing houseplants and starting seeds for the coming spring. It's a time of dreaming and planning, as we envision the garden reborn in the warmth of the sun.In the cycle of the seasons, we find a rhythm that connects us to the natural world. Each season offers its own joys and challenges, reminding us of the beauty and wonder of life's ever-changing tapestry. And as we tend to our gardens, we cultivate not just plants, but a deeper connection to the earth and to ourselves.",bottomNavigationBar: const ExploreBottomNavigationBar(),),
        bottomNavigationBar: const ExploreBottomNavigationBar());
  }
}
