import 'package:flutter/material.dart';
import 'package:flutter_app_for_exam2/NewsApp/utils/widgets/articles_widgets/articles_controller.dart';
import 'package:flutter_app_for_exam2/NewsApp/utils/widgets/explore_widgets/explore_bottom_navigation_bar.dart';
class Article8Page extends StatelessWidget {
  const Article8Page({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: ArticlesController(image: "assets/images/explore_page/image4.png",title: "Chasing the Northern Lights: A Winter in Finland",avatar: "assets/images/explore_page/woman3.png",text1: "Jeannie · May 12, 2023",text2: "Chasing the Northern Lights in Finland is an enchanting adventure that promises to ignite the imagination and awaken the soul. As winter descends upon this northern wonderland, the stage is set for a magical spectacle of dancing lights in the night sky, painting an ethereal canvas of colors and patterns that seem to defy earthly explanation.The journey begins in the pristine wilderness of Finnish Lapland, where snow-capped forests and frozen lakes stretch as far as the eye can see. Here, amidst the silence of the Arctic landscape, travelers embark on a quest to witness one of nature's most awe-inspiring phenomena—the Aurora Borealis.Venturing into the wilderness, visitors can choose from a variety of experiences to maximize their chances of seeing the Northern Lights. From guided snowmobile safaris and husky sledding expeditions to reindeer sleigh rides and snowshoeing adventures, there are endless opportunities to explore the winter wonderland under the starry skies.As night falls, the real magic begins. Wrapped in warm layers and equipped with cameras and tripods, adventurers gather in anticipation, scanning the heavens for the first signs of the elusive auroras. Suddenly, a faint glow appears on the horizon, growing brighter and more vibrant with each passing moment until it erupts into a dazzling display of greens, purples, and blues swirling overhead in a mesmerizing dance of light.Under the guidance of experienced local guides and aurora hunters, travelers are treated to front-row seats to nature's greatest light show. From secluded wilderness campsites to cozy lakeside cabins and glass igloos, there are endless vantage points from which to witness the spectacle, each offering its own unique charm and sense of wonder.But the Northern Lights are just one aspect of winter in Finland's Lapland. During the day, adventurers can immerse themselves in a myriad of winter activities, from cross-country skiing and snowshoeing to ice fishing and traditional Finnish sauna rituals. For the more adventurous, there are opportunities to try ice climbing, snowboarding, and even sleeping in an ice hotel.As the days grow shorter and the nights longer, Finland's northernmost regions become a playground for winter enthusiasts and nature lovers alike. Whether marveling at the Northern Lights from a reindeer-drawn sleigh or enjoying a traditional Lappish feast under the stars, a winter in Finland is an unforgettable journey into the heart of the Arctic wilderness, where magic and wonder await at every turn.",bottomNavigationBar: const ExploreBottomNavigationBar(),),
        bottomNavigationBar: const ExploreBottomNavigationBar());
  }
}
