import 'package:flutter/material.dart';
import 'package:flutter_app_for_exam2/NewsApp/utils/widgets/articles_widgets/articles_controller.dart';
import 'package:flutter_app_for_exam2/NewsApp/utils/widgets/articles_widgets/bottom_navigation_bar_controller.dart';
import 'package:flutter_app_for_exam2/NewsApp/utils/widgets/bookmark_widgets/bookmark_bottom_navigation_bar.dart';
class Article12Page extends StatelessWidget {
  const Article12Page({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: ArticlesController(image: "assets/images/bookmark_page/image3.png",title: "Exploring the World's Best Beaches: Top 5 Picks",avatar: "assets/images/explore_page/woman1.png",text1: "Sophie Andreson · May 18, 2023",text2: "Embarking on a journey to explore the world's best beaches unveils a treasure trove of stunning coastal landscapes and pristine shores. Here are five top picks for some of the most breathtaking beaches around the globe:\n1. Whitehaven Beach, Australia: Tucked away in the heart of the Great Barrier Reef, Whitehaven Beach is renowned for its powdery white silica sand and crystal-clear turquoise waters. Stretching over seven kilometers along Whitsunday Island, this idyllic beach offers unrivaled opportunities for swimming, snorkeling, and beachcombing amidst its untouched natural beauty.\n2. Anse Source d'Argent, Seychelles: Located on the island of La Digue in the Seychelles archipelago, Anse Source d'Argent is a picture-perfect paradise of granite boulders, palm-fringed shores, and shallow turquoise lagoons. Visitors can stroll along the soft white sands, swim in the warm waters, and bask in the tranquility of this iconic beach.\n3. Navagio Beach (Shipwreck Beach), Greece: Nestled within a dramatic cove on the island of Zakynthos, Navagio Beach is famous for its shipwrecked vessel resting on its golden sands. Accessible only by boat, this secluded beach is surrounded by towering cliffs and vibrant blue waters, creating a breathtaking backdrop for sunbathing, swimming, and photography.\n4. Matira Beach, Bora Bora: Situated on the southwestern tip of Bora Bora in French Polynesia, Matira Beach is celebrated for its soft white sands and shallow, crystal-clear lagoon. Framed by lush greenery and swaying palm trees, this postcard-perfect beach offers opportunities for swimming, snorkeling, and kayaking in the warm, tropical waters of the South Pacific.\n5. Tulum Beach, Mexico: Nestled along the Riviera Maya on Mexico's Yucatan Peninsula, Tulum Beach is renowned for its powdery white sands, turquoise Caribbean waters, and ancient Mayan ruins overlooking the sea. Visitors can explore the archaeological site of Tulum, relax on the pristine beach, and enjoy a laid-back atmosphere infused with bohemian charm.These top picks for the world's best beaches offer travelers a chance to escape to paradise and experience the sheer beauty and serenity of some of the most stunning coastal destinations on the planet. Whether you're seeking adventure, relaxation, or simply a slice of paradise, these breathtaking beaches are sure to captivate and inspire.",bottomNavigationBar: const BottomNavigationBarController(),),
        bottomNavigationBar: const BookmarkBottomNavigationBar());
  }
}